name: Lint

on:
  push:
    branches-ignore:
      - "renovate/*"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hadolint
        run: |
          hadolint --version
          hadolint */Dockerfile
