name: Build and publish

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: metabotter/nextcloud

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian@sha256:cfb21dfaf9514e2260011558816d3971f5ab8eb5dbb0381b70461a290168817e
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: hadolint
        run: |
          hadolint --version
          hadolint */Dockerfile

  nextcloud_27:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "27"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version number
        run: |
          VER=$(grep "FROM nextcloud:" ${{ env.VERSION }}/Dockerfile)
          VER=${VER#*:}
          VER=${VER%@*}
          VER=${VER%-*}
          echo "IMAGE_VERSION=$VER" >> $GITHUB_ENV

      - name: Build and publish
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ env.VERSION }}/Dockerfile
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"
      
      - name: Send message to Nextcloud talk
        run: |
          curl -X POST ${{ secrets.NEXTCLOUD_TALK_URL }}/${{ secrets.NEXTCLOUD_CHAT_ID }} --user '${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_APP_PASSWORD }}' --header 'OCS-APIRequest: true' --data-urlencode 'message=Nextcloud ${{ env.VERSION }} image has been updated'
  
  nextcloud_28:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "28"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version number
        run: |
          VER=$(grep "FROM nextcloud:" ${{ env.VERSION }}/Dockerfile)
          VER=${VER#*:}
          VER=${VER%@*}
          VER=${VER%-*}
          echo "IMAGE_VERSION=$VER" >> $GITHUB_ENV

      - name: Build and publish
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ env.VERSION }}/Dockerfile
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"
      
      - name: Send message to Nextcloud talk
        run: |
          curl -X POST ${{ secrets.NEXTCLOUD_TALK_URL }}/${{ secrets.NEXTCLOUD_CHAT_ID }} --user '${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_APP_PASSWORD }}' --header 'OCS-APIRequest: true' --data-urlencode 'message=Nextcloud ${{ env.VERSION }} image has been updated'

  nextcloud_29:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "29"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version number
        run: |
          VER=$(grep "FROM nextcloud:" ${{ env.VERSION }}/Dockerfile)
          VER=${VER#*:}
          VER=${VER%@*}
          VER=${VER%-*}
          echo "IMAGE_VERSION=$VER" >> $GITHUB_ENV

      - name: Build and publish
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ env.VERSION }}/Dockerfile
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"
      
      - name: Send message to Nextcloud talk
        run: |
          curl -X POST ${{ secrets.NEXTCLOUD_TALK_URL }}/${{ secrets.NEXTCLOUD_CHAT_ID }} --user '${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_APP_PASSWORD }}' --header 'OCS-APIRequest: true' --data-urlencode 'message=Nextcloud ${{ env.VERSION }} image has been updated'
 
  nextcloud_30:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "30"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version number
        run: |
          VER=$(grep "FROM nextcloud:" ${{ env.VERSION }}/Dockerfile)
          VER=${VER#*:}
          VER=${VER%@*}
          VER=${VER%-*}
          echo "IMAGE_VERSION=$VER" >> $GITHUB_ENV

      - name: Build and publish
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ env.VERSION }}/Dockerfile
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}"
      
      - name: Send message to Nextcloud talk
        run: |
          curl -X POST ${{ secrets.NEXTCLOUD_TALK_URL }}/${{ secrets.NEXTCLOUD_CHAT_ID }} --user '${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_APP_PASSWORD }}' --header 'OCS-APIRequest: true' --data-urlencode 'message=Nextcloud ${{ env.VERSION }} image has been updated'
