name: Test build

on: pull_request

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: hadolint
        run: |
          hadolint --version
          hadolint */Dockerfile

  nextcloud_24:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "24"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_25:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "25"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_26:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "26"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_27:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "27"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_28:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "28"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"
