name: Test build

on: pull_request

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian@sha256:9cef74a390694cdc01dd119cbba9adac5bb6671ce67d8d79eb7ec68f497a3684
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: hadolint
        run: |
          hadolint --version
          hadolint */Dockerfile

  nextcloud_27:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "27"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_28:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "28"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_29:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "29"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

      - name: Send message to Nextcloud talk
        run: |
          curl -X POST ${{ secrets.NEXTCLOUD_TALK_URL }}/${{ secrets.NEXTCLOUD_CHAT_ID }} --user '${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_APP_PASSWORD }}' --header 'OCS-APIRequest: true' --data-urlencode 'message=Nextcloud ${{ env.VERSION }} image has been tested'
 

  nextcloud_30:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "30"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"
