name: ci

on: pull_request

jobs:
  nextcloud_test_22:
    runs-on: ubuntu-latest
    steps:
      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: 22/Dockerfile
