name: Test build

on: pull_request

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian@sha256:9cef74a390694cdc01dd119cbba9adac5bb6671ce67d8d79eb7ec68f497a3684
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hadolint
        run: |
          hadolint --version
          hadolint */Dockerfile

  nextcloud_24:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "24"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_25:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "25"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_26:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "26"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: "${{ env.VERSION }}/Dockerfile"
