name: Test build

on: pull_request

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian@sha256:cfb21dfaf9514e2260011558816d3971f5ab8eb5dbb0381b70461a290168817e
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: hadolint
        run: |
          hadolint --version
          hadolint */Dockerfile

  nextcloud_27:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "27"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_28:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "28"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_29:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "29"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"

  nextcloud_30:
    runs-on: ubuntu-latest
    needs:
      - lint_dockerfile
    env:
      VERSION: "30"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: "${{ env.VERSION }}/Dockerfile"
